export default {
    ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
    ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
    ON_SEARCH_INPUT: "ON_SEARCH_INPUT",
    COOKIE_CHECK: "COOKIE_CHECK",
    FILL_CART: "FILL_CART",
}